kind: Deployment
apiVersion: apps/v1
metadata:
   name: k8s_devops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: k8s_devops
   template:
      metadata:
        labels:
          app: k8s_devops
      spec:
       containers:
        - name: k8s_devops
          image: ishpreetsingh0/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
