kind: Service                             
apiVersion: v1
metadata:
  name: k8s_devops
  labels:
    app: k8s_devops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: k8s_devops                    
  type: LoadBalancer                   
